2-models
JuankDawd/kommit_bootcamp_blog_api pull request #5
Opened 2021-11-09 17:30 UTC by JuankDawd

1-initial-commit

2021-11-09 19:35 UTC, luishurtado requested changes

2021-11-09 19:35 UTC, luishurtado commented on db/migrate/20211109172516_create_items.rb
> +      t.boolean :done
Can these columns be null? Do they have default values?

2021-11-09 19:41 UTC, JuankDawd commented on db/migrate/20211109172516_create_items.rb
> +      t.boolean :done
In the project, the name column is set to be needed, but not the done column.

2021-11-11 00:22 UTC, luishurtado approved these changes

2021-11-11 00:24 UTC, merged